
title: Punky IT
url: 'http://punky-it.co'
baseurl: '/punkyit.github.io' #change it according to your repository name



# Profile information
yourname: Diedra Steward  ## put your name
title: 'Aspiring Tech Wizard'  ## your title
location: Grand Rapids, MI


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
